### ISSUE TITLE
Invalid_argument Cstruct.set_len

### ISSUE THREAD

**Issue by anmonteiro** [mirage/mirage-net-macosx#33] opened 2019-03-14 13:16 UTC
I'm seeing what seems to be an infinite loop with the following logs:

```
2019-03-14 13:16:23 +00:00: INF [net-macosx] Netif: connect unknown
2019-03-14 13:16:23 +00:00: INF [ethernet] Connected Ethernet interface e6:0f:ea:40:b3:71
2019-03-14 13:16:23 +00:00: ERR [net-macosx] [netif-input] error : (Invalid_argument "Cstruct.set_len [0,1514](1514) 4294966293")
2019-03-14 13:16:23 +00:00: ERR [net-macosx] [netif-input] error : (Invalid_argument "Cstruct.set_len [0,1514](1514) 4294966293")
2019-03-14 13:16:23 +00:00: ERR [net-macosx] [netif-input] error : (Invalid_argument "Cstruct.set_len [0,1514](1514) 4294966293")
.....
```

**Comment by MagnusS** [comment] 2019-09-17 11:28
Thanks for the report! This should now be fixed in the latest release (1.7.0). The issue was caused by a combination of the wrong buffer length being passed to ocaml-vmnet and the error then not being reported correctly.

**Closed as completed by MagnusS** 2019-09-17 11:28 UTC
